apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-rdf-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-rdf-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-rdf-exporter
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
