apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: k8s-rdf-exporter

resources:
  - ../../base/ # This includes the base resources
  - rbac.yaml
