apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-rdf-exporter
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-rdf-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-rdf-exporter
roleRef:
  kind: Role
  name: k8s-rdf-exporter
  apiGroup: rbac.authorization.k8s.io
